services:
  fcp-fdm:
    build:
      context: .
      target: development
    depends_on:
      mongodb:
        condition: service_healthy
      floci-init:
        condition: service_completed_successfully
    environment:
      MONGO_URI: mongodb://mongodb:27017
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SQS_QUEUE_URL: http://floci:4566/000000000000/fcp_fdm_events
      AWS_ENDPOINT_URL: http://floci:4566
      AUTH_ENABLED: ${AUTH_ENABLED:-false}
      AUTH_TENANT_ID: ${AUTH_TENANT_ID}
      AUTH_ALLOWED_GROUP_IDS: ${AUTH_ALLOWED_GROUP_IDS}
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  mongodb:
    image: mongo:7.0.24
    command: --replSet rs0 --bind_ip_all --port 27017
    attach: false
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 10s

  floci:
    image: hectorvent/floci:latest
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/init.sh
    depends_on:
      floci:
        condition: service_started
    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./floci/init.sh:/setup/init.sh

  fcp-fdm-event-publisher-stub:
    image: defradigital/fcp-fdm-event-publisher-stub
    depends_on:
      floci-init:
        condition: service_completed_successfully
    environment:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:fcp_event_publisher
      AWS_ENDPOINT_URL: http://floci:4566
