services:
  fcp-fdm:
    build:
      target: development
    command: npm test
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./test:/home/node/test
      - ./coverage:/home/node/coverage
